class RADWIMPS
  VERSION: String
  RAISE: Method

  def initialize: (?strict: bool) -> void
  def then: () -> self
  def raise: () -> self
  def set: () -> void

  private

  def format_counter: () -> String
end
