class RADWIMPS
  VERSION: String
  RAISE: Method

  @strict: bool
  @life_counter: Integer

  def initialize: (?strict: bool) -> void
  def then: () -> self
  def raise: () -> self
  def set: () -> void

  private

  def format_counter: () -> String
end

class RADWIMPS::Error < StandardError
end